version: '2'
services:
    sampleapplication-app:
        image: sampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@sampleapplication-oracle:1521:SampleApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
